version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
      - npm run build
  pre_build:
    commands:
      - npm install
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
  upload-artifacts: yes
  logs: yes
